version: 3.3.0.{build}
image: Visual Studio 2019

skip_branch_with_pr: true
skip_tags: true
skip_commits:
  files:
    - '**/*.md'

environment:
  CLICKHOUSE_CONNECTION: Host=localhost;Port=8123

nuget:
  project_feed: true
  disable_publish_on_pr: true

services:
- docker

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

before_build:
- dotnet restore

build_script:
- dotnet build --no-restore --configuration Release

before_test:
- docker version
- docker pull yandex/clickhouse-server
- docker run -m 3GB -p 8123:8123 -d --name clickhouse-server yandex/clickhouse-server
- sleep 3

test_script:
- dotnet test --no-build --framework netcoreapp3.1 --configuration Release --test-adapter-path:. --logger:Appveyor

artifacts:
- path: '**/*nupkg'
  name: NuGet
