version: 2.2.2.{build}
image:
  - Visual Studio 2019
  - Ubuntu

skip_branch_with_pr: true
skip_tags: true
skip_commits:
  files:
    - '**/*.md'

environment:
  CLICKHOUSE_CONNECTION: Host=localhost;Port=8123

nuget:
  project_feed: true
  disable_publish_on_pr: true

services:
- docker

install:
- dotnet tool install --global Codecov.Tool

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

before_build:
- dotnet restore

build_script:
- dotnet build --no-restore --configuration Release

before_test:
- docker version
- docker pull yandex/clickhouse-server
- docker run -m 3GB -p 8123:8123 -d --name clickhouse-server yandex/clickhouse-server
- sleep 3

test_script:
- dotnet test --no-build --framework netcoreapp3.0 --configuration Release --test-adapter-path:. --logger:Appveyor

for:
- matrix:
    only:
      - image: Ubuntu
  build_script:
  - msbuild /p:Configuration=Release -verbosity:minimal
- matrix:
    only:
      - image: Visual Studio 2019
  after_build:
  - dotnet pack ClickHouse.Client/ClickHouse.Client.csproj --no-build --configuration Release --include-symbols --include-source -p:SymbolPackageFormat=snupkg
  artifacts:
  - path: '**/*nupkg'
    name: NuGet
