# Release build
# Needs to be clean
# Should never install additional packages
name: Release from tag

on:
  push:
    tags:
      - '*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build & pack
      id: build_pack
      run: dotnet build --configuration Release /p:Version=${{ github.ref_name }}

    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: ClickHouse.Client/bin/Release/ClickHouse.Client.*nupkg

  push_github:
    runs-on: windows-latest
    needs: [build]    
    name: Upload to GitHub Packages
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: package

    - name: Push package
      id: push
      shell: cmd
      run: dotnet nuget push ClickHouse.Client.*.nupkg --skip-duplicate --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json

  push_nuget_org:
    runs-on: windows-latest
    needs: [build]
    name: Upload to NuGet.org
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: package
      
    - name: Push package
      id: push
      shell: cmd
      run: dotnet nuget push ClickHouse.Client.*.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json

  github_release:
    runs-on: ubuntu-latest
    needs: [build]
    name: Create GitHub release
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: package
    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "*.nupkg,*.snupkg"
        generateReleaseNotes: true
        draft: false
        prerelease: false
